Cn.Com.Sve.OA.Web/Controllers/StudentHomeVisitRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cn.Com.Sve.OA.BusinessService;
using Cn.Com.Sve.OA.Entities;
using Cn.Com.Sve.OA.Entities.Criteria;
using Cn.Com.Sve.OA.Web.Models;
using Cn.RaymanLee.Web.UI.ViewModels.LigerUI;
using Cn.RaymanLee.Data;
using Cn.Com.Sve.OA.Web.Models.ViewModels;

namespace Cn.Com.Sve.OA.Web.Controllers {
	public partial class StudentHomeVisitRecordController : BaseController {
		private object ToJson(StudentHomeVisitRecord e) {
			return new {
				Id = e.Id,
				ClazzId = e.ClazzId,
				StudentId = e.StudentId,
				Time = e.Time,
				VisitType = e.VisitType,
				BeginTime = e.BeginTime,
				EndTime = e.EndTime,
				GiveContactCard = e.GiveContactCard,
				Visitees = e.Visitees,
				PhoneNo = e.PhoneNo,
				Visitors = e.Visitors,
				Advice = e.Advice,
				Summary = e.Summary,
				ReviewerId = e.ReviewerId,
				ReviewTime = e.ReviewTime,
				ReviewComment = e.ReviewComment,
				InputUserId = e.InputUserId
			};
		}
    

		partial void AddRowToGridModel(LigerGridModel m, StudentHomeVisitRecord e) {
			m.Rows.Add(this.ToJson(e));
		}
		partial void AfterAddData(StudentHomeVisitRecord e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		partial void AfterUpdateData(StudentHomeVisitRecord e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}

		public ActionResult GetInitData() {
			return this.Json(new { }, JsonRequestBehavior.AllowGet);
		}


		private Student_HomeVisit_ViewModel BuildVisitViewModel(int studentId) {
			var m = new Student_HomeVisit_ViewModel();
			var studentService = new StudentService(new SysContext { CurrentUser = AppContext.CurrentUser });
			m.Student = studentService.FindById(studentId);
			m.Records = this.Service.FindByStudentId(studentId).OrderByDescending(o => o.Time).ToList();
			return m;
		}

		[HttpGet]
		public ActionResult Input(int id) {
			var m = this.BuildVisitViewModel(id);
			m.ShowInput = true;
			m.CurrentUser = AppContext.CurrentUser;
			return this.View("DisplayByStudent", m);
		}
		[HttpPost]
		public ActionResult Input(StudentHomeVisitRecord r) {
			this.Service.Add(r);
			var m = this.BuildVisitViewModel(r.StudentId);
			m.ShowInput = true;
			m.CurrentUser = AppContext.CurrentUser;
			return this.View("DisplayByStudent", m);
		}
		[HttpGet]
		public ActionResult EditInfo(int id) {
			var r = this.Service.FindById(id);
			if (r != null) {
				return this.View(r);
			} else {
				return this.Content("未找到指定记录！");
			}
		}
		[HttpPost]
		public ActionResult EditInfo(StudentHomeVisitRecord r) {
			this.Service.Update(r);
			this.ViewBag.Msg = "操作成功！";
			r = this.Service.FindById(r.Id);
			return this.View(r);
		}

		[HttpGet]
		public ActionResult DeleteInfo(int id) {
			var r = this.Service.FindById(id);
			if (r != null) {
				int sid = r.StudentId;
				this.Service.DeleteById(id);
				var m = this.BuildVisitViewModel(r.StudentId);
				m.ShowInput = true;
				m.CurrentUser = AppContext.CurrentUser;
				return this.View("DisplayByStudent", m);
			} else {
				return this.Content("未找到指定记录！");
			}
		}
		[HttpGet]
		public ActionResult EditConfirm(int id) {
			var r = this.Service.FindById(id);
			if (r != null) {
				this.ViewBag.User = AppContext.CurrentUser;
				return this.View(r);
			} else {
				return this.Content("未找到指定记录！");
			}
		}
		[HttpPost]
		public ActionResult EditConfirm(StudentHomeVisitRecord r) {
			this.Service.Update(r);
			this.ViewBag.Msg = "操作成功！";
			r = this.Service.FindById(r.Id);

			return this.View(r);
		}

		[HttpGet]
		public ActionResult Search() {
			var m = new Student_HomeVisit_ViewModel {
				Criteria = new StudentHomeVisitRecordCriteria(),
				CurrentUser = AppContext.CurrentUser,
				Records = new List<StudentHomeVisitRecord>(),
				ShowConfirmEdit = true,
				ShowDelete = true,
				ShowInput = false
			};
			m.Criteria.TimeFromSrh = DateTime.Today.AddDays(-7);
			m.Criteria.TimeToSrh = DateTime.Today.AddDays(1);
			return this.View(m);
		}
		[HttpPost]
		public ActionResult Search(StudentHomeVisitRecordCriteria c) {
			c.sortname = "time";
			c.sortorder = "desc";
			var m = new Student_HomeVisit_ViewModel {
				Criteria = c,
				CurrentUser = AppContext.CurrentUser,
				Records = this.Service.Search(c).Data,
				ShowConfirmEdit = true,
				ShowDelete = true,
				ShowInput = false
			};
			return this.View(m);
		}

	}
}

Cn.Com.Sve.OA.Web/Views/StudentHomeVisitRecord/DisplayByStudent.cshtml
@model Cn.Com.Sve.OA.Web.Models.ViewModels.Student_HomeVisit_ViewModel

@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Gray/css/all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/ligerui-icons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/css/common.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Content/lib/jquery/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.widget.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.position.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.autocomplete.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/ligerUI/js/ligerui.all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.metadata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/messages_cn.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.form.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/LG.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/json2.js")" type="text/javascript"></script>
    <style type="text/css">
        body
        {
            font-size: 12px;
        }
        .l-table-edit
        {
        }
        .l-table-edit-td
        {
            padding: 4px;
        }
        .l-button-submit, .l-button-reset
        {
            width: 80px;
            float: left;
            margin-left: 10px;
            padding-bottom: 2px;
        }
        .l-verify-tip
        {
            left: 230px;
            top: 120px;
            z-index: 9999;
        }
    </style>
	<style type="text/css">
	.ui-autocomplete-loading { background: white url('@Url.Content("~/Content/themes/base/images/ui-anim_basic_16x16.gif")') right center no-repeat; }
	#f_UserName { width: 25em; }
	</style>
    <script type="text/javascript">
        $(function () {
            $("#Time").ligerDateEditor({ initValue: '@String.Format("{0:d}",DateTime.Today)' });
            $("#frmCondition").ligerForm();

        });
    </script>
</head>
<body style="padding: 10px; height: 100%; text-align: center;">
    <div id="pnlStudentInfo" style="width: 98%">
        <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px; border: 1 solid black;" border="1">
            <tr><td class='l-table-edit-td'>班级：@this.Model.Student.Clazz.Name</td><td class='l-table-edit-td'>学员姓名：@this.Model.Student.Name</td>
            <td class='l-table-edit-td'>性别：@this.Model.Student.Gender</td>
            
            <td class='l-table-edit-td'>学员手机：@this.Model.Student.Mobile</td>
            <td class='l-table-edit-td'>家访次数：@this.Model.Records.Count</td></tr>
        </table>
    </div>
    @if (this.Model.ShowInput) { 
     <div id="pnlByForm" style="width: 98%">
             <form id="frmCondition" class="l-form" action='@Url.Action("Input","StudentHomeVisitRecord")' method="post" enctype="multipart/form-data">
                <input type="hidden" name="StudentId" value="@this.Model.Student.Id" />
                <input type="hidden" name="ClazzId" value="@this.Model.Student.ClazzId" />
                <input type="hidden" name="InputUserId" value="@this.Model.CurrentUser.Id" />

                <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px">
                    <tr>
                        <td class='l-table-edit-td'>家访类型</td><td class='l-table-edit-td'>
                            <select id="VisitType" name="VisitType">
                                <option value="平常家访">平常家访</option>
                                <option value="五一家访">五一家访</option>
                                <option value="国庆家访">国庆家访</option>
                                <option value="春节家访">春节家访</option>
                            </select>
                        </td>
                        <td class='l-table-edit-td'>家访日期</td><td class='l-table-edit-td'><input type='text' id='Time' name="Time" ltype='text' /></td>
                    </tr>
                    <tr>
                        <td class='l-table-edit-td'>开始时间</td><td class='l-table-edit-td'><input type='text' id='BeginTime' name="BeginTime" ltype='text' /></td>
                        <td class='l-table-edit-td'>结束时间</td><td class='l-table-edit-td'><input type='text' id='EndTime' name="EndTime" ltype='text' /></td>
                    </tr>
                    <tr>
                        <td class='l-table-edit-td'>家访对象</td><td class='l-table-edit-td'><input type='text' id='Visitees' name="Visitees" ltype='text' /></td>
                        <td class='l-table-edit-td'>家长电话</td><td class='l-table-edit-td'><input type='text' id='PhoneNo' name="PhoneNo" ltype='text' /></td>
                    </tr>
                    <tr>
                        <td class='l-table-edit-td'>家访人员</td><td class='l-table-edit-td'><input type='text' id='Visitors' name="Visitors" ltype='text' /></td>
                        <td class='l-table-edit-td'>家长联系卡</td><td class='l-table-edit-td'>
                            <input type='radio' name="GiveContactCard" ltype='radio' value="已送" checked="checked" />已送
                            <input type='radio' name="GiveContactCard" ltype='radio' value="未送" />未送
                        </td>
                    </tr>
                    <tr><td colspan="4" class='l-table-edit-td'>意见和建议：<br /><textarea name='Advice' id='Advice' ltype='text' class="l-textarea" style="width:100%;height:200;"></textarea></td></tr>
                    <tr><td colspan="4" class='l-table-edit-td'>家访总结：<br /><textarea name='Summary' id='Summary' ltype='text' class="l-textarea" style="width:100%;height:200;"></textarea></td></tr>
                    <tr><td colspan="4" class='l-table-edit-td'><input type="submit" id="btnAdd" value="录入" /></td></tr>
                </table>
             </form>
    </div>
    }
    <div id="pnlByRecords" style="width: 98%">
    @foreach (var t in this.Model.Records) {
        <div style="margin-bottom:5px;">
            <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px; border: 1 solid black;" border="1">
                <tr>
                    <td class='l-table-edit-td'>家访类型：@t.VisitType</td>
                    <td class='l-table-edit-td'>家访日期：@String.Format("{0:d}", t.Time)</td>
                    <td class='l-table-edit-td'>开始时间：@t.BeginTime</td>
                    <td class='l-table-edit-td'>结束时间：@t.EndTime</td>
                </tr>
                <tr>
                    <td class='l-table-edit-td'>家访对象：@t.Visitees</td>
                    <td class='l-table-edit-td'>家长电话：@t.PhoneNo</td>
                    <td class='l-table-edit-td'>家访人员：@t.Visitors</td>
                    <td class='l-table-edit-td'>家长联系卡：@t.GiveContactCard</td>
                </tr>
                <tr><td class='l-table-edit-td' colspan="4">意见和建议：<br />@t.Advice</td></tr>
                <tr><td class='l-table-edit-td' colspan="4">家访总结：<br />@t.Summary</td></tr>
                @if (t.ReviewerId != null) {
                <tr>
                    <td class='l-table-edit-td' colspan="2">抽查人员：@t.Reviewer.Name</td>
                    <td class='l-table-edit-td'  colspan="2">抽查日期：@String.Format("{0:d}", t.ReviewTime)</td>
                </tr>
                <tr><td class='l-table-edit-td' colspan="4">抽查情况：<br /><span style="color:red;">@t.ReviewComment</span></td></tr>
                }
                <tr>
                    <td class='l-table-edit-td' colspan="4" align="center">
                        @if (t.InputUserId.Equals(this.Model.CurrentUser.Id)) {
                            <a href="#" onclick="top.f_addTab('tab-edit-student-homevisit-@t.Id', '编辑家访记录', '@Url.Action("EditInfo", "StudentHomeVisitRecord")' + '?id=@t.Id');return false;">编辑</a>
                            <a href='@Url.Action("DeleteInfo", "StudentHomeVisitRecord", new { id=t.Id })' onclick="if(!window.confirm('确定要删除吗？'))return false;">删除</a>
                        } else {
                            if (this.Model.ShowDelete) {
                                <a href='@Url.Action("DeleteInfo", "StudentHomeVisitRecord", new { id = t.Id })' onclick="if(!window.confirm('确定要删除吗？'))return false;">删除</a>
                            }
                            if ((t.ReviewerId.HasValue && t.ReviewerId.Equals(this.Model.CurrentUser.Id)) || this.Model.ShowConfirmEdit) {
                            <a href="#" onclick="top.f_addTab('tab-edit-student-homevisit-c-@t.Id', '编辑家访记录', '@Url.Action("EditConfirm", "StudentHomeVisitRecord")' + '?id=@t.Id');return false;">编辑抽查情况</a>
                            }
                        }
                    </td>
                </tr>
            </table>
        </div>
    }
    </div>


</body>
</html>

Cn.Com.Sve.OA.Web/Views/StudentHomeVisitRecord/EditConfirm.cshtml
@model Cn.Com.Sve.OA.Entities.StudentHomeVisitRecord

@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Gray/css/all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/ligerui-icons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/css/common.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Content/lib/jquery/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.widget.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.position.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.autocomplete.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/ligerUI/js/ligerui.all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.metadata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/messages_cn.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.form.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/LG.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/json2.js")" type="text/javascript"></script>
    <style type="text/css">
        body
        {
            font-size: 12px;
        }
        .l-table-edit
        {
        }
        .l-table-edit-td
        {
            padding: 4px;
        }
        .l-button-submit, .l-button-reset
        {
            width: 80px;
            float: left;
            margin-left: 10px;
            padding-bottom: 2px;
        }
        .l-verify-tip
        {
            left: 230px;
            top: 120px;
            z-index: 9999;
        }
    </style>
	<style type="text/css">
	.ui-autocomplete-loading { background: white url('@Url.Content("~/Content/themes/base/images/ui-anim_basic_16x16.gif")') right center no-repeat; }
	#f_UserName { width: 25em; }
	</style>
    <script type="text/javascript">
        $(function () {
            $("#ReviewTime").ligerDateEditor({ initValue: '@String.Format("{0:d}",this.Model.ReviewTime)' });
            $("#frmCondition").ligerForm();
        });
    </script>
    @if(this.ViewBag.Msg!=null) { 
    <script type="text/javascript">
        $(function () {
            LG.showSuccess('@this.ViewBag.Msg ！');
        });
    </script>
    }

</head>
<body style="padding: 10px; height: 100%; text-align: center;">
     <div id="pnlByForm" style="width: 98%">
             <form id="frmCondition" class="l-form" action='@Url.Action("EditConfirm", "StudentHomeVisitRecord")' method="post" enctype="multipart/form-data">
                <input type="hidden" name="Id" value="@this.Model.Id" />
                <input type="hidden" name="StudentId" value="@this.Model.Student.Id" />
                <input type="hidden" name="ClazzId" value="@this.Model.Student.ClazzId" />
                <input type="hidden" name="Visitors" value="@this.Model.Visitors" />
                <input type="hidden" name="Visitees" value="@this.Model.Visitees" />
                <input type="hidden" name="VisitType" value="@this.Model.VisitType" />
                <input type="hidden" name="BeginTime" value="@this.Model.BeginTime" />
                <input type="hidden" name="EndTime" value="@this.Model.EndTime" />
                <input type="hidden" name="GiveContactCard" value="@this.Model.GiveContactCard" />
                <input type="hidden" name="PhoneNo" value="@this.Model.PhoneNo" />

                <input type="hidden" name="Time" value="@this.Model.Time" />
                <input type="hidden" name="Advice" value="@this.Model.Advice" />
                <input type="hidden" name="Summary" value="@this.Model.Summary" />
                <input type="hidden" name="ReviewerId" value="@(this.Model.ReviewerId.HasValue ? this.Model.Reviewer.Id : this.ViewBag.User.Id)" />

                <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px" border="1">
                <tr>
                    <td class='l-table-edit-td'>家访类型：@this.Model.VisitType</td>
                    <td class='l-table-edit-td'>家访日期：@String.Format("{0:d}", this.Model.Time)</td>
                </tr>
                <tr>
                    <td class='l-table-edit-td'>开始时间：@this.Model.BeginTime</td>
                    <td class='l-table-edit-td'>结束时间：@this.Model.EndTime</td>
                </tr>
                <tr>
                    <td class='l-table-edit-td'>家访对象：@this.Model.Visitees</td>
                    <td class='l-table-edit-td'>家长电话：@this.Model.PhoneNo</td>
                </tr>
                <tr>
                    <td class='l-table-edit-td'>家访人员：@this.Model.Visitors</td>
                    <td class='l-table-edit-td'>家长联系卡：@this.Model.GiveContactCard</td>
                </tr>
                <tr><td class='l-table-edit-td' colspan="2">意见和建议：<br />@this.Model.Advice</td></tr>
                <tr><td class='l-table-edit-td' colspan="2">家访总结：<br />@this.Model.Summary</td></tr>
                <tr>
                    <td class='l-table-edit-td'>抽查人员</td><td class='l-table-edit-td'>@(this.Model.ReviewerId.HasValue?this.Model.Reviewer.Name:this.ViewBag.User.Name)</td>
                    <td class='l-table-edit-td'>抽查日期</td><td class='l-table-edit-td' ><input type='text' id='ReviewTime' name="ReviewTime" ltype='text' /></td>

                </tr>
                <tr><td class='l-table-edit-td' colspan="2">抽查情况：<br />
                <textarea name='ReviewComment' id='ReviewComment' ltype='text' class="l-textarea" style="width:100%;height:200;">@this.Model.ReviewComment</textarea>
                </td></tr>
                    <tr><td colspan="4" class='l-table-edit-td'><input type="submit" id="btnAdd" value="保存" /></td></tr>
                </table>
             </form>
    </div>
</body>
</html>