Cn.Com.Sve.OA.Web/Models/ViewModels/TeleSaleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Cn.Com.Sve.OA.Entities;
namespace Cn.Com.Sve.OA.Web.Models.ViewModels {
	/// <summary>
	/// 录入电访记录界面的视图模型
	/// </summary>
	[Serializable]
	public class TeleSaleViewModel {
		public Customer Customer { get; set; }
	}
}

Cn.Com.Sve.OA.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cn.Com.Sve.OA.BusinessService;
using Cn.Com.Sve.OA.Entities;
using Cn.Com.Sve.OA.Entities.Criteria;
using Cn.Com.Sve.OA.Web.Models;
using Cn.RaymanLee.Web.UI.ViewModels.LigerUI;
using Cn.RaymanLee.Data;
using Cn.Com.Sve.OA.Web.Models.ViewModels;

namespace Cn.Com.Sve.OA.Web.Controllers {
	public partial class CustomerController : BaseController {
		//public IBigInfoSourceService BigInfoSourceService { get; set; }
		//public ISmallInfoSourceService SmallInfoSourceService { get; set; }
		//public IImportCustomerService ImportCustomerService { get; set; }
		#region 分部方法
		private object ToJson(Customer e) {
			return new {
				Id = e.Id,
				Name = e.Name,
				SchoolId = e.SchoolId,
				MarketYear = e.MarketYear,
				Telephone = e.Telephone,
				Mobile = e.Mobile,
				Clazz = e.Clazz,
				Gender = e.Gender,
				QQ = e.QQ,
				Email = e.Email,
				EduLevel = e.EduLevel,
				IsGaoKao = e.IsGaoKao,
				GaoKaoScore = e.GaoKaoScore,
				GaoKaoBatch = e.GaoKaoBatch,
				DistrictId = e.DistrictId,
				Address = e.Address,
				Postcode = e.Postcode,
				SmallInfoSourceId = e.SmallInfoSourceId,
				ConsultType = e.ConsultType,
				Remark = e.Remark,
				ConsultantId1 = e.ConsultantId1,
				ConsultantId2 = e.ConsultantId2,
				NetConsultantId = e.NetConsultantId,
				CreateTeacherId = e.CreateTeacherId,
				ConsultTime = e.ConsultTime,
				SalesTeamId = e.SalesTeamId,
				SalesmanId = e.SalesmanId,
				IsImport = e.IsImport,
				TeleSalesTimes = e.TeleSalesTimes,
				NextTeleSalesTime = e.NextTeleSalesTime.HasValue ? String.Format("{0:yyyy-MM-dd HH:mm}",e.NextTeleSalesTime.Value) : "",
				AppointmentTime = e.AppointmentTime,
				DropInTime = e.DropInTime,
				DinWeiTime = e.DinWeiTime,
				SignUpTime = e.SignUpTime,
				IsDinWei = e.IsDinWei,
				IsClosed = e.IsClosed,
				Important = e.Important,
				ConsultantRemark = e.ConsultantRemark,
				Keywords = e.Keywords,
				IsLeaderFollow = e.IsLeaderFollow,
				Status = e.Status,
				LastSalesTime = e.LastSalesTime,
				LastSaleLog = e.LastSaleLog,
				InClazzId = e.InClazzId,
				InClazzName = e.InClazzName,
				ConsultantName1 = e.ConsultantName1,
				ConsultantName2 = e.ConsultantName2,
				ProvinceName = e.ProvinceName,
				CityName = e.CityName,
				DistrictName = e.DistrictName,
				SchoolName = e.SchoolName,
				SalesTeamName = e.SalesTeamName,
				SalesmanName = e.SalesmanName,
				IsDorm = e.IsDorm
			};
			#region OLD
			//return new {
			//    Id = e.Id,
			//    Name = e.Name,
			//    SchoolId = e.SchoolId,
			//    MarketYear = e.MarketYear,
			//    Telephone = e.Telephone,
			//    Mobile = e.Mobile,
			//    Clazz = e.Clazz,
			//    Gender = e.Gender,
			//    QQ = e.QQ,
			//    Email = e.Email,
			//    EduLevel = e.EduLevel,
			//    IsGaoKao = e.IsGaoKao,
			//    GaoKaoScore = e.GaoKaoScore,
			//    GaoKaoBatch = e.GaoKaoBatch,
			//    DistrictId = e.DistrictId,
			//    Address = e.Address,
			//    Postcode = e.Postcode,
			//    SmallInfoSourceId = e.SmallInfoSourceId,
			//    ConsultType = e.ConsultType,
			//    Remark = e.Remark,
			//    ConsultantId1 = e.ConsultantId1,
			//    ConsultantId2 = e.ConsultantId2,
			//    NetConsultantId = e.NetConsultantId,
			//    CreateTeacherId = e.CreateTeacherId,
			//    ConsultTime = e.ConsultTime,
			//    SalesTeamId = e.SalesTeamId,
			//    SalesmanId = e.SalesmanId,
			//    IsImport = e.IsImport,
			//    TeleSalesTimes = e.TeleSalesTimes,
			//    NextTeleSalesTime = e.NextTeleSalesTime,
			//    AppointmentTime = e.AppointmentTime,
			//    DropInTime = e.DropInTime,
			//    DinWeiTime = e.DinWeiTime,
			//    SignUpTime = e.SignUpTime,
			//    IsDinWei = e.IsDinWei,
			//    IsClosed = e.IsClosed,
			//    Important = e.Important,
			//    ConsultantRemark = e.ConsultantRemark,
			//    Keywords = e.Keywords,
			//    IsLeaderFollow = e.IsLeaderFollow,
			//    Status = e.Status,
			//    LastSalesTime = e.LastSalesTime,
			//    LastSaleLog = e.LastSaleLog,
			//    InClazzId = e.InClazzId,
			//    InClazzName = (e.InClazz == null) ? "" : e.InClazz.Name,
			//    ConsultantName1 = (e.Consultant1 == null) ? "" : e.Consultant1.Name,
			//    ConsultantName2 = (e.Consultant2 == null) ? "" : e.Consultant2.Name,
			//    ProvinceName = (e.District == null || e.District.City == null || e.District.City.Province == null) ? "" : e.District.City.Province.Name,
			//    CityName = (e.District == null || e.District.City == null) ? "" : e.District.City.Name,
			//    DistrictName = (e.District == null) ? "" : e.District.Name,
			//    SchoolName = e.School.Name,
			//    SalesTeamName = (e.SalesTeam == null) ? "" : e.SalesTeam.Name,
			//    SalesmanName = (e.Salesman == null) ? "" : e.Salesman.Name,
			//    IsDorm = e.IsDorm
			//};
			#endregion
		}

		partial void AddRowToGridModel(LigerGridModel m, Customer e) {
			m.Rows.Add(this.ToJson(e));
		}
		partial void AfterAddData(Customer e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		partial void AfterUpdateData(Customer e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		#endregion
		
		public ActionResult GetInitData() {
			#region 省市区数据
			IProvinceService provService = new ProvinceService(new SysContext { CurrentUser = AppContext.CurrentUser });
			ICityService cityService = new CityService(new SysContext { CurrentUser = AppContext.CurrentUser });
			IDistrictService districtService = new DistrictService(new SysContext { CurrentUser = AppContext.CurrentUser });
			var provinces = provService.FindAll();
			var cities = cityService.FindAll();
			var districts = districtService.FindAll();

			List<object> provs = new List<object>();

			provinces.ForEach(o => {
				var p = new { Id = o.Id, Name = o.Name, Cities = new List<object>() };
				cities.Where(c => c.ProvinceId.Equals(o.Id)).ToList().ForEach(c => {
					var city = new { Id = c.Id, Name = c.Name, Districts = new List<object>() };
					districts.Where(d => d.CityId.Equals(c.Id)).ToList().ForEach(d => {
						city.Districts.Add(new { Id = d.Id, Name = d.Name });
					});
					p.Cities.Add(city);
				});
				provs.Add(p);
			});
			#endregion

			#region 招生小组
			ISalesTeamService teamService = new SalesTeamService(new SysContext { CurrentUser = AppContext.CurrentUser });
			ISalesTeamMemberService memberService = new SalesTeamMemberService(new SysContext { CurrentUser = AppContext.CurrentUser });
			var ts = teamService.FindAll();
			var ms = memberService.FindAll();
			var teams = new List<object>();

			ts.ForEach(o => {
				var t = new { Id = o.Id, Name = o.Name, Members = new List<object>() };
				ms.Where(m => m.SalesTeamId.Equals(o.Id)).ToList().ForEach(m => {
					t.Members.Add(new { Id = m.Id, Name = m.User.Name, UserId = m.UserId, IsLeader = m.IsLeader });
				});
				teams.Add(t);
			});
			#endregion

			return this.Json(new { Provinces = provs, Teams = teams }, JsonRequestBehavior.AllowGet);
		}

		#region 导入数据

		[HttpGet]
		public ActionResult Import() {
			// 默认招生年份，9月份以前默认为本年，9月份开始默认为下一年
			if (DateTime.Today.Month < 9) {
				this.ViewBag.MarketingYear = DateTime.Today.Year;
			} else {
				this.ViewBag.MarketingYear = DateTime.Today.Year + 1;
			}
			return this.View();
		}
		[HttpPost]
		public ActionResult ImportBySchool(int? SchoolId, string Level, int? MarketingYear, int? BigSourceId, int? SmallSourceId, bool? chkDelOld) {
			if (!SchoolId.HasValue) { 
				return this.Content("找不到相应的学校！");
			}
			if (!MarketingYear.HasValue) {
				return this.Content("请填写正确的招生年份！");
			}
			if (!BigSourceId.HasValue || !SmallSourceId.HasValue) {
				return this.Content("请选择正确的信息来源！");
			}
			if (this.Request.Files["File"] == null) {
				return this.Content("请选择正确的数据文件！");
			}
			var key = Guid.NewGuid().ToString();
			var filename = @"d:\tempdata\" + key + ".xls";
			try {
				this.Request.Files["File"].SaveAs(filename);
			} catch (Exception ex) {
				return this.Content(String.Format("保存上传文件时发生错误，内部错误为{0}。", ex.Message));
			}
			//var filename = @"d:\tempdata\91b630c2-bf32-410b-b0a4-3b7e69891c23.xls";
			var r = this.Service.ImportBySchool(key, SchoolId.Value, Level, MarketingYear.Value, SmallSourceId.Value, filename, chkDelOld.GetValueOrDefault());
			if (r.Successful) {
				int rn1 = 0, rn2=0;
				if (r.DuplicateQty > 0) {
					rn1 = 1;
				}
				if (r.ErrorQty > 0) {
					rn2 = 1;
				}
				return this.Content(String.Format(
					"OK-{6}-{7}-{0}-总记录数：{1}，添加数量：{2}，更新数量：{3}，重复数量：{4}，错误数量：{5}。"
					,key,r.TotalQty,r.AddedQty,r.UpdatedQty,r.DuplicateQty,r.ErrorQty,rn1,rn2
				));
			} else {
				return this.Content(r.ErrorMessage);
			}
			//return this.Content("msg");
			//return this.Json(new AjaxOperationResult { Successful = true });
			//this.ViewBag.MarketingYear = MarketingYear;
			//return this.View("Import");			
		}
		[HttpPost]
		public ActionResult ImportByChannel(string Level, int? MarketingYear, int? BigSourceId2, int? SmallSourceId2) {
			if (!MarketingYear.HasValue) {
				return this.Content("请填写正确的招生年份！");
			}
			if (!BigSourceId2.HasValue || !SmallSourceId2.HasValue) {
				return this.Content("请选择正确的信息来源！");
			}
			if (this.Request.Files["File"] == null) {
				return this.Content("请选择正确的数据文件！");
			}
			var key = Guid.NewGuid().ToString();
			var filename = @"d:\tempdata\" + key + ".xls";
			try {
				this.Request.Files["File"].SaveAs(filename);
			} catch (Exception ex) {
				return this.Content(String.Format("保存上传文件时发生错误，内部错误为{0}。", ex.Message));
			}
			//var filename = @"d:\tempdata\91b630c2-bf32-410b-b0a4-3b7e69891c23.xls";

Cn.Com.Sve.OA.Web/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cn.Com.Sve.OA.BusinessService;
using Cn.Com.Sve.OA.Entities;
using Cn.Com.Sve.OA.Entities.Criteria;
using Cn.Com.Sve.OA.Web.Models;
using Cn.RaymanLee.Web.UI.ViewModels.LigerUI;
using Cn.RaymanLee.Data;
using Cn.Com.Sve.OA.Web.Models.ViewModels;

namespace Cn.Com.Sve.OA.Web.Controllers {
	public partial class SchoolController : BaseController {
		public ISchoolAdService SchoolAdService { get; set; }
		private object ToJson(School e) {
			return new {
				Id = e.Id,
				Name = e.Name,
				DistrictId = e.DistrictId,
				DistrictName = (e.District == null) ? "" : e.District.Name,
				CityId = (e.District == null || e.District.City == null) ? "" : e.District.City.Id.ToString(),
				CityName = (e.District == null || e.District.City == null) ? "" : e.District.City.Name,
				ProvinceId = (e.District == null || e.District.City == null || e.District.City.Province == null) ? "" : e.District.City.Province.Id.ToString(),
				ProvinceName = (e.District == null || e.District.City == null || e.District.City.Province == null) ? "" : e.District.City.Province.Name,
				IsSold = e.IsSold,
				FullDistrictName = e.District.FullName,
				Levels = e.Levels,
				Type = e.Type,
				DevBy = e.DevBy,
				DevDate = e.DevDate.HasValue ? e.DevDate.Value.ToString("yyyy-MM-dd") : "",
				Important = e.Important.GetValueOrDefault() ? "是" : "否"
			};
		}

		partial void AddRowToGridModel(LigerGridModel m, School e) {
			m.Rows.Add(this.ToJson(e));
		}
		partial void AfterAddData(School e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		partial void AfterUpdateData(School e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		
		public ActionResult GetInitData() {
			IProvinceService provService = new ProvinceService(new SysContext { CurrentUser = AppContext.CurrentUser });
			ICityService cityService = new CityService(new SysContext { CurrentUser = AppContext.CurrentUser });
			IDistrictService districtService = new DistrictService(new SysContext { CurrentUser = AppContext.CurrentUser });
			var provinces = provService.FindAll();
			var cities = cityService.FindAll();
			var districts = districtService.FindAll();
			
			List<object> m = new List<object>();

			provinces.ForEach(o => {
				var p = new { Id = o.Id, Name = o.Name, Cities = new List<object>() };
				cities.Where(c => c.ProvinceId.Equals(o.Id)).ToList().ForEach(c => { 
					var city = new { Id = c.Id, Name = c.Name, Districts = new List<object>() };
					districts.Where(d => d.CityId.Equals(c.Id)).ToList().ForEach(d => {
						city.Districts.Add(new { Id = d.Id, Name = d.Name });
					});
					p.Cities.Add(city);
				});
				m.Add(p);
			});
			return this.Json(new { Provinces = m }, JsonRequestBehavior.AllowGet);
		}

		public ActionResult Suggest(string prefix, int qty) {
			List<object> m = new List<object>();
			var r = this.Service.FindByCriteria(new SchoolCriteria { NameSrh = prefix, pagesize = qty, sortname = "name", sortorder = "asc" });
			r.Data.ForEach(o => {
				m.Add(new { Id = o.Id, Name = o.Name });
			});
			return this.Json(m, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// 渠道学校资料维护入口
		/// </summary>
		/// <returns></returns>
		public ActionResult HuWai() {
			return View();
		}
		/// <summary>
		/// 渠道学校资料维护入口页的查询
		/// </summary>
		/// <param name="c"></param>
		/// <returns></returns>
		public ActionResult GetDataForHuWai(SchoolCriteria c) {
			var m = new LigerGridModel();
			this.BeforeGetData(c);
			var r = this.Service.FindByCriteria(c);
			this.AfterGetData(m, c, r);
			m.Total = r.RecordCount;
			r.Data.ForEach(o => {
				this.AddRowToGridModel(m, o);
			});
			this.AfterBuildGridModel(m, c, r);
			return this.Json(m, JsonRequestBehavior.AllowGet);
		}
		/// <summary>
		/// 渠道学校 - 学校基本信息
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		public ActionResult HuWaiDisplay(int id) {
			//var m = new School_HuWaiDisplay_ViewModel();
			//m.School = this.Service.FindById(id);
			//m.SchoolAds = this.SchoolAdService.FindBySchoolId(id);
			return this.View(this.Service.FindById(id));
		}
		/// <summary>
		/// 根据学校ID读取校园宣传资料情况
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		public ActionResult GetAdBySchoolId(int id) {
			this.SchoolAdService = new SchoolAdService(new SysContext { CurrentUser = AppContext.CurrentUser });
			var list = this.SchoolAdService.FindBySchoolId(id);
			var m = new LigerGridModel();
			m.Total = list.Count;
			list.ForEach(o => {
				m.Rows.Add(new {
					BuTiao = o.BuTiao,
					DaoJiShiPai = o.DaoJiShiPai,
					GuaLi = o.GuaLi,
					HighClassQty = o.HighClassQty,
					HighStudentQty = o.HighStudentQty,
					Id = o.Id,
					JiaoShiBiaoYu = o.JiaoShiBiaoYu,
					LouTiBiaoYu = o.LouTiBiaoYu,
					LowClassQty = o.LowClassQty,
					LowStudentQty = o.LowStudentQty,
					ShiTangBiaoYu = o.ShiTangBiaoYu,
					ShuShiBiaoYu = o.ShuShiBiaoYu,
					TaiLi = o.TaiLi,
					Year = o.Year
				});
			});
			return this.Json(m, JsonRequestBehavior.AllowGet);
		}
		public ActionResult DeleteAd(int id) {
			return null;
		}
	}
}

Cn.Com.Sve.OA.Web/Views/Customer/LeaderFollow.cshtml
@{
    Layout = null;
}
<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Gray/css/all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/ligerui-icons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/css/common.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Content/lib/jquery/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.widget.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.position.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.autocomplete.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/ligerUI/js/ligerui.all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.metadata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/messages_cn.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.form.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/LG.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/json2.js")" type="text/javascript"></script>
    <style type="text/css">
        body
        {
            font-size: 12px;
        }
        .l-table-edit
        {
        }
        .l-table-edit-td
        {
            padding: 4px;
        }
        .l-button-submit, .l-button-reset
        {
            width: 80px;
            float: left;
            margin-left: 10px;
            padding-bottom: 2px;
        }
        .l-verify-tip
        {
            left: 230px;
            top: 120px;
            z-index: 9999;
        }
    </style>
	<style>
	.ui-autocomplete-loading { background: white url('@Url.Content("~/Content/themes/base/images/ui-anim_basic_16x16.gif")') right center no-repeat; }
	#f_UserName { width: 25em; }
	</style>
        <script type="text/javascript">
            var gCustomer;
            var action = "add";
            var $dialog;
            var initData;
            var rnd = Math.random();

            $(function () {
                gCustomer = $("#grdCustomer").ligerGrid({
                    url: '@Url.Action("Search", "Customer")',
                    parms: [
                { name: 'IsLeaderFollowSrh', value: 'true' },
                { name: 'SalesTeamIdSrh', value: $("#SalesTeamIdSrh").val() },
                { name: 'SchoolNameSrh', value: $("#f_SchoolNameSrh").val() },
                { name: 'KeywordsSrh', value: $("#KeywordsSrh").val() },
                { name: 'SalesmanNameSrh', value: $("#SalesmanNameSrh").val() },
                { name: 'NameSrh', value: $("#NameSrh").val() },
                { name: 'TelephoneSrh', value: $("#TelephoneSrh").val() },
                { name: 'ImportantSrh', value: $("#ImportantSrh").get(0).checked },
                { name: 'IsTodaySrh', value: $("#IsTodaySrh").get(0).checked }
                ],
                columns: [
					{ display: '姓名', name: 'Name', width: 60, align: 'left' },
					{ display: '学校', name: 'SchoolName', width: 100, align: 'left' },
					{ display: '高考成绩', name: 'GaoKaoScore', width: 100, align: 'left', type: 'int' },
					{ display: '类别', name: 'ConsultType', width: 100, align: 'left' },
					{ display: '组员姓名', name: 'SalesmanName', width: 100, align: 'left' },
                    { display: '关键词', name: 'Keywords', width: 100, align: 'left' }
                  ],
                    pageSize: 20,
                    sortName: 'Name',
                    width: '98%', height: '100%', checkbox: false,
                    usePager: true,
                    onSelectRow: function (data, rowindex, rowobj) {
                        top.f_addTab("tab-addtellog-" + data.Id, data.Name, '@Url.Action("TeleSale","Customer")' + "?customerId=" + data.Id);
                    }
                });

                $.getJSON('@Url.Action("GetInitData", "Customer")', function (data) {
                    initData = data

                    $("#frmCondition").ligerForm();
                });

                $("#f_SchoolNameSrh").autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            url: '@Url.Action("Suggest","School")',
                            dataType: "json",
                            data: {
                                qty: 12,
                                prefix: request.term
                            },
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return {
                                        label: item.Name,
                                        value: item.Id
                                    }
                                }));
                            }
                        });
                    },
                    minLength: 1,
                    select: function (event, ui) {
                        $("#SchoolIdSrh").val(ui.item.value);
                        $("#f_SchoolNameSrh").val(ui.item.label);
                        return false;
                    },
                    open: function () {
                        $(this).removeClass("ui-corner-all").addClass("ui-corner-top");
                    },
                    close: function () {
                        $(this).removeClass("ui-corner-top").addClass("ui-corner-all");
                    }
                });

                $("#btnSearch").click(function () {
                    search();
                });

                search();
            });

            function search(){
                gCustomer.set({
                    url: '@Url.Action("Search", "Customer")',
                    parms: [
                { name: 'IsLeaderFollowSrh', value: 'true' },
                { name: 'SalesTeamIdSrh', value: $("#SalesTeamIdSrh").val() },
                { name: 'SchoolNameSrh', value: $("#f_SchoolNameSrh").val() },
                { name: 'KeywordsSrh', value: $("#KeywordsSrh").val() },
                { name: 'SalesmanNameSrh', value: $("#SalesmanNameSrh").val() },
                { name: 'NameSrh', value: $("#NameSrh").val() },
                { name: 'TelephoneSrh', value: $("#TelephoneSrh").val() },
                { name: 'ImportantSrh', value: $("#ImportantSrh").get(0).checked },
                { name: 'IsTodaySrh', value: $("#IsTodaySrh").get(0).checked }
                ]
                });
                gCustomer.loadData();
                gCustomer.changePage("first");
            }
    </script>
</head>
<body style="padding: 10px; height: 100%; text-align: center;">
    <div id="pnlByCondition" style="width: 98%">
             <form id="frmCondition" class="l-form" action='' method="post" enctype="multipart/form-data">
             <input type="hidden" id="SalesTeamIdSrh" name="SalesTeamIdSrh" value='@this.ViewBag.TeamId' />
                <table cellpadding="0" cellspacing="0" class="l-table-edit">
                <tr>
                    <td style='text-align: right;' class='l-table-edit-td'>
                        姓名
                    </td>
                    <td style='text-align: left;' class='l-table-edit-td'>
                        <input type='text' id='NameSrh' name="NameSrh" ltype='text' />
                    </td>
                    <td style='text-align: right;' class='l-table-edit-td'>
                        联系方式
                    </td>
                    <td style='text-align: left;' class='l-table-edit-td'>
                        <input type='text' id='TelephoneSrh' name="TelephoneSrh" ltype='text' />
                    </td>
                    <td style='text-align: right;' class='l-table-edit-td'>
                        学校名称
                    </td>
                    <td style='text-align: left;' class='l-table-edit-td' >
                        <input name='SchoolNameSrh' type='text' id='f_SchoolNameSrh' ltype='text' />
                        <input name='SchoolIdSrh' type='hidden' id='SchoolIdSrh' />
                    </td>
                </tr>
                <tr>
                    <td style='text-align: right;' class='l-table-edit-td'>
                        组员
                    </td>
                    <td style='text-align: left;' class='l-table-edit-td'>
                       <input name='SalesmanNameSrh' type='text' id='SalesmanNameSrh' ltype='text' />
                    </td>
                    <td style='text-align: right;' class='l-table-edit-td'>
                        关键词
                    </td>
                    <td style='text-align: left;' class='l-table-edit-td'>
                        <input type='text' id='KeywordsSrh' name="KeywordsSrh" ltype='text' />
                    </td>
                     <td style='text-align: right;' class='l-table-edit-td'>
                        <input type='checkbox' id='ImportantSrh' name="ImportantSrh" ltype='text' />&nbsp;重点客户
                    </td>
                    <td style='text-align: left;' class='l-table-edit-td'>
                        <input type='checkbox' id='IsTodaySrh' name="IsTodaySrh" ltype='text' />&nbsp;今天需要回访
                    </td>


                    <td style="text-align:center">
                        <input type="button" id="btnSearch" value="查询" />
                    </td>
                   
                </tr>
                </table>
            </form>

            <div id="grdCustomer"></div> 

    </div>

</body>
</html>