Cn.Com.Sve.OA.Web/Controllers/QualificationSchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cn.Com.Sve.OA.BusinessService;
using Cn.Com.Sve.OA.Entities;
using Cn.Com.Sve.OA.Entities.Criteria;
using Cn.Com.Sve.OA.Web.Models;
using Cn.RaymanLee.Web.UI.ViewModels.LigerUI;
using Cn.RaymanLee.Data;

namespace Cn.Com.Sve.OA.Web.Controllers {
	public partial class QualificationSchoolController : BaseController {
		private object ToJson(QualificationSchool e) {
			return new {
				Id = e.Id,
				Name = e.Name
			};
		}

		partial void AddRowToGridModel(LigerGridModel m, QualificationSchool e) {
			m.Rows.Add(this.ToJson(e));
		}
		partial void AfterAddData(QualificationSchool e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		partial void AfterUpdateData(QualificationSchool e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}

		public ActionResult GetInitData() {
			return this.Json(new { }, JsonRequestBehavior.AllowGet);
		}
	}
}

Cn.Com.Sve.OA.Web/Views/QualificationSchool/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Gray/css/all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/ligerui-icons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/css/common.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Content/lib/jquery/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/ligerUI/js/ligerui.all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.metadata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/messages_cn.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/LG.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/json2.js")" type="text/javascript"></script>
    <style type="text/css">
        body {
            font-size: 12px;
        }

        .l-table-edit {
        }

        .l-table-edit-td {
            padding: 4px;
        }

        .l-button-submit, .l-button-reset {
            width: 80px;
            float: left;
            margin-left: 10px;
            padding-bottom: 2px;
        }

        .l-verify-tip {
            left: 230px;
            top: 120px;
            z-index: 9999;
        }
    </style>
    <script type="text/javascript">
        var gQualificationSchool;
        var action = "add";
        var $dialog;
        var initData;

        $(function () {
            gQualificationSchool = $("#grdQualificationSchool").ligerGrid({
                columns: [
					{ display: '名称', name: 'Name', width: '98%', align: 'left' }
                ],
                pageSize: 20, toolbar: {},
                url: '@Url.Action("GetData", "QualificationSchool")',
                sortName: 'Name',
                width: '98%', height: '100%', checkbox: false,
                usePager: true,
                toolbar: {
                    items: [
                    { text: '增加', icon: 'add', click: addQualificationSchool },
                    { line: true },
                    { text: '修改', icon: 'modify', click: editQualificationSchool },
                    { line: true },
                    { text: '删除', icon: 'delete', click: deleteQualificationSchool }
                    ]
                }
            });
            $("#btnSearch").click(function () {
                gQualificationSchool.set({
                    parms: [
					{ name: '名称', value: $('#NameSrh').val() }
                    ]
                });
                gQualificationSchool.loadData();
            });

            $.validator.addMethod(
	            "notnull",
	            function (value, element, regexp) {
	                if (!value) return true;
	                return !$(element).hasClass("l-text-field-null");
	            },
	            "不能为空"
            );

            $.metadata.setType("attr", "validate");
            var v = $("#frmQualificationSchool").validate({
                errorPlacement: function (lable, element) {
                    if (element.hasClass("l-textarea")) {
                        element.addClass("l-textarea-invalid");
                    } else if (element.hasClass("l-text-field")) {
                        element.parent().addClass("l-text-invalid");
                    }
                    $(element).removeAttr("title").ligerHideTip();
                    $(element).attr("title", lable.html()).ligerTip();
                },
                success: function (lable) {
                    var element = $("#" + lable.attr("for"));
                    if (element.hasClass("l-textarea")) {
                        element.removeClass("l-textarea-invalid");
                    } else if (element.hasClass("l-text-field")) {
                        element.parent().removeClass("l-text-invalid");
                    }
                    $(element).removeAttr("title").ligerHideTip();
                },
                submitHandler: function () {
                    saveQualificationSchool();
                    return false;
                }
            });

            $.getJSON("@Url.Action("GetInitData", "QualificationSchool")", function (data) {
                initData = data;
                $("#formsearch").ligerForm();
                $("#frmQualificationSchool").ligerForm();
            });


        });

        function addQualificationSchool() {
            action = "add";
            $("#f_QualificationSchool_Id").val("");
            $("#f_QualificationSchool_Name").val("");
            $dialog = $.ligerDialog.open({ target: $("#dQualificationSchool"), width: 300, height: 150 });
        }
        function editQualificationSchool() {
            action = "edit";
            var row = gQualificationSchool.getSelectedRow();
            if (!row) { LG.tip('请选择行!'); return }
            $("#f_QualificationSchool_Id").val(row.Id);
            $("#f_QualificationSchool_Name").val(row.Name);
            $dialog = $.ligerDialog.open({ target: $("#dQualificationSchool"), width: 300, height: 150 });
        }
        function deleteQualificationSchool() {
            var row = gQualificationSchool.getSelectedRow();
            if (!row) { LG.tip('请选择行!'); return }

            $.ligerDialog.confirm("您确定要删除选中记录么？", function (r) {
                if (r) {
                    $.post("@Url.Action("Delete", "QualificationSchool")", { id: row.Id }
                        , function (result) {
                            if (result.Successful) {
                                gQualificationSchool.deleteSelectedRow();
                            } else {
                                $.ligerMessageBox.error('错误', result.Message);
                            }
                        }
                    );
                }
            });
        }
        function saveQualificationSchool() {
            if (action == "add") {
                $.post("@Url.Action("Add", "QualificationSchool")", $("#frmQualificationSchool").serialize(),
                    function (result) {
                        if (result.Successful) {
                            gQualificationSchool.addRow(result.Data);
                            $dialog.hidden();
                            LG.tip("操作成功！");
                        } else {
                            LG.showError(result.Message);
                        }
                    }
                );
            } else {
                $.post("@Url.Action("Update", "QualificationSchool")", $("#frmQualificationSchool").serialize(),
                    function (result) {
                        if (result.Successful) {
                            var row = gQualificationSchool.getSelected();
                            if (!row) { alert('请选择行'); return; }
                            gQualificationSchool.updateRow(row, result.Data);
                            $dialog.hidden();
                            LG.tip("操作成功！");
                        } else {
                            LG.showError(result.Message);
                        }
                    }
                );
            }
        }
    </script>
</head>
<body style="padding: 10px; height: 100%; text-align: center;">
    <div id="mainsearch" style="width: 98%">
        <div class="searchtitle">
            <span>搜索</span><img src="@Url.Content("~/Content/lib/icons/32X32/searchtool.gif")" alt="" />
            <div class="togglebtn">
            </div>
        </div>
        <div class="navline" style="margin-bottom: 4px; margin-top: 4px;">
        </div>
        <div class="searchbox">
            <form id="formsearch" class="l-form" action="">
                <table cellpadding="0" cellspacing="0" class="l-table-edit">
                    <tr>
                        <td style='text-align: right;' class='l-table-edit-td'>
                            名称
                        </td>
                        <td style='text-align: left;' class='l-table-edit-td'>
                            <input name='NameSrh' type='text' id='NameSrh' ltype='text' />
                        </td>

                        <td style="text-align: center;" class="l-table-edit-td" colspan="3">
                            <input type="button" value="查询" id="btnSearch" />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div id="grdQualificationSchool">
    </div>
    <div id="dQualificationSchool" style="display: none;">
        <form action="" method="post" id="frmQualificationSchool">
            <input type="hidden" id="f_QualificationSchool_Id" name="Id" value="" />
            <table cellpadding="0" cellspacing="0" class="l-table-edit">
                <tr>
                    <td class='l-table-edit-td' style='text-align: right;'>
                        名称
                    </td>
                    <td class='l-table-edit-td' style='text-align: left; width: 160px'>
                        <input name='Name' type='text' id='f_QualificationSchool_Name' ltype='text' />
                    </td>
                    <td style='text-align: left;'></td>
                </tr>
                <tr>
                    <td colspan="3" style="text-align: center;">
                        <input type="submit" id="btnProvinceSave" value="保存" class="l-button l-button-submit" />
                        <input type="button" id="btnProvinceCancel" value="取消" onclick='$dialog.hidden();'
                               class="l-button l-button-reset" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>