Cn.Com.Sve.OA.Web/Controllers/EmploymentCompanyContactVisitLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cn.Com.Sve.OA.BusinessService;
using Cn.Com.Sve.OA.Entities;
using Cn.Com.Sve.OA.Entities.Criteria;
using Cn.Com.Sve.OA.Web.Models;
using Cn.RaymanLee.Web.UI.ViewModels.LigerUI;
using Cn.RaymanLee.Data;


namespace Cn.Com.Sve.OA.Web.Controllers {
	public partial class EmploymentCompanyContactVisitLogController : BaseController {
		private object ToJson(EmploymentCompanyContactVisitLog e) {
			return new {
				Id = e.Id,
				CompanyContactId = e.CompanyContactId,
				Time = e.Time,
				VisitorId = e.VisitorId,
				Type = e.Type,
				Content = e.Content
			};
		}

		partial void AddRowToGridModel(LigerGridModel m, EmploymentCompanyContactVisitLog e) {
			m.Rows.Add(this.ToJson(e));
		}
		partial void AfterAddData(EmploymentCompanyContactVisitLog e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		partial void AfterUpdateData(EmploymentCompanyContactVisitLog e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}

		public ActionResult GetInitData() {
			return this.Json(new { }, JsonRequestBehavior.AllowGet);
		}
		// 添加访谈信息
		[HttpGet]
		public ActionResult AddNew(int contactId) {
			var s = new EmploymentCompanyContactService(new SysContext { CurrentUser = AppContext.CurrentUser });
			var m = new EmploymentCompanyContactVisitLog { Time = DateTime.Today, Type = "电访" };
			this.ViewBag.Contact=s.FindById(contactId);
			this.ViewBag.Visitor=AppContext.CurrentUser;
			return this.View(m);
		}
		[HttpPost]
		public ActionResult AddNew(EmploymentCompanyContactVisitLog e) {
			try {
				this.Service.Add(e);
				e = this.Service.FindById(e.Id);
			} catch (Exception ex) {
				return this.Content(ex.Message);
			}
			return this.RedirectToAction("Display", "EmploymentCompany", new { id = e.CompanyContact.CompanyId });
		}
		public ActionResult EditSync(int id) {
			var e = this.Service.FindById(id);
			if (e != null) {
				this.BeforeShowEditView(e);
				return this.View(e);
			} else {
				return this.Content("找不到数据！");
			}
		}
		[HttpPost]
		public ActionResult UpdateSync(EmploymentCompanyContactVisitLog e) {
			this.Service.Update(e);
			e = this.Service.FindById(e.Id);
			return this.RedirectToAction("Display", "EmploymentCompany", new { id = e.CompanyContact.CompanyId });
		}
		[HttpGet]
		public ActionResult DeleteSync(int id) {
			var e = this.Service.FindById(id);
			var s = new EmploymentCompanyContactService(new SysContext { CurrentUser = AppContext.CurrentUser });
			var c = s.FindById(e.CompanyContactId);

			this.Service.DeleteById(id);
			return this.RedirectToAction("Display", "EmploymentCompany", new { id = c.CompanyId });
		}
	}
}

Cn.Com.Sve.OA.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cn.Com.Sve.OA.BusinessService;
using Cn.Com.Sve.OA.Entities;
using Cn.Com.Sve.OA.Entities.Criteria;
using Cn.Com.Sve.OA.Web.Models;
using Cn.RaymanLee.Web.UI.ViewModels.LigerUI;
using Cn.RaymanLee.Data;

namespace Cn.Com.Sve.OA.Web.Controllers {
	public partial class UserController : BaseController {
		private object ToJson(User e) {
			return new {
				Id = e.Id,
				Name = e.Name,
				Password = e.Password,
				Status = e.Status,
				LastLoginTime = e.LastLoginTime,
				LastLoginIP = e.LastLoginIP
			};
		}
		partial void AddRowToGridModel(LigerGridModel m, User e) {
			m.Rows.Add(this.ToJson(e));
		}
		partial void AfterAddData(User e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}
		partial void AfterUpdateData(User e, ref ActionResult ar) {
			ar = this.Json(new AjaxOperationResult {
				Data = this.ToJson(e),
				Successful = true
			});
		}

		partial void BeforeAddData(User e, ref ActionResult ar) {
			e.Status = "正常";
			if (!String.IsNullOrEmpty(e.NewPassword)) {
				e.Password = e.NewPassword;
			}
		}
		partial void BeforeUpdateData(User e, ref ActionResult ar) {
			if (!String.IsNullOrEmpty(e.NewPassword)) {
				e.Password = e.NewPassword;
			}
		}

		public ActionResult GetInitData() {
			return this.Json(new {}, JsonRequestBehavior.AllowGet);
		}

		public ActionResult Suggest(string prefix, int qty) {
			List<object> m = new List<object>();
			var r = this.Service.FindByCriteria(new UserCriteria { NameSrh = prefix, pagesize = qty, sortname = "name", sortorder = "asc" });
			r.Data.ForEach(o => {
				m.Add(new { Id = o.Id, Name = o.Name });
			});
			return this.Json(m, JsonRequestBehavior.AllowGet);
		}
	}
}

Cn.Com.Sve.OA.Web/Views/EmploymentCompanyContactVisitLog/AddNew.cshtml
@model Cn.Com.Sve.OA.Entities.EmploymentCompanyContactVisitLog

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Gray/css/all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/ligerui-icons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/css/common.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Content/lib/jquery/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.widget.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.position.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.autocomplete.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/ligerUI/js/ligerui.all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.metadata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/messages_cn.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.form.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/LG.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/json2.js")" type="text/javascript"></script>
    <style type="text/css">
        body {
            font-size: 12px;
        }

        .l-table-edit {
        }

        .l-table-edit-td {
            padding: 4px;
        }

        .l-button-submit, .l-button-reset {
            width: 80px;
            float: left;
            margin-left: 10px;
            padding-bottom: 2px;
        }

        .l-verify-tip {
            left: 230px;
            top: 120px;
            z-index: 9999;
        }
    </style>
    <style type="text/css">
	.ui-autocomplete-loading { background: white url('@Url.Content("~/Content/themes/base/images/ui-anim_basic_16x16.gif")') right center no-repeat; }
	#f_UserName { width: 25em; }
    </style>
    <script type="text/javascript">
        $(function () {
            $("#Time").ligerDateEditor({ initValue: '@String.Format("{0:d}",this.Model.Time)' });
            $("#f_VisitorId").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("Suggest","User")',
                        dataType: "json",
                        data: {
                            qty: 12,
                            prefix: request.term
                        },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item.Name,
                                    value: item.Id
                                }
                            }));
                        }
                    });
                },
                minLength: 1,
                select: function (event, ui) {
                    $("#VisitorId").val(ui.item.value);
                    $("#f_VisitorId").val(ui.item.label);
                    return false;
                },
                open: function () {
                    $(this).removeClass("ui-corner-all").addClass("ui-corner-top");
                },
                close: function () {
                    $(this).removeClass("ui-corner-top").addClass("ui-corner-all");
                }
            });
            $("#frmCondition").ligerForm();

            $("#VisitorId").val("@this.ViewBag.Visitor.Id");
            $("#f_VisitorId").val("@this.ViewBag.Visitor.Name");

        });
    </script>
</head>
<body style="padding: 10px; height: 100%; text-align: center;">
    <div id="pnlStudentInfo" style="width: 98%">
        <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px; border: 1 solid black;" border="1">
            <tr>
                <td class='l-table-edit-td'>就业企业：@this.ViewBag.Contact.Company.Name</td>
                <td class='l-table-edit-td'>联系人：@this.ViewBag.Contact.Name</td>
                <td class='l-table-edit-td'>职务：@this.ViewBag.Contact.Position</td>
                <td class='l-table-edit-td'>手机：@this.ViewBag.Contact.Mobile</td>
            </tr>
            <tr>
                <td class='l-table-edit-td'>电话：@this.ViewBag.Contact.Telephone</td>
                <td class='l-table-edit-td'>QQ：@this.ViewBag.Contact.QQ</td>
                <td class='l-table-edit-td'>邮箱：@this.ViewBag.Contact.Email</td>
                <td class='l-table-edit-td'>备注：@this.ViewBag.Contact.Introduction</td>
            </tr>
        </table>
    </div>
    <div id="pnlByForm" style="width: 98%">
        <form id="frmCondition" class="l-form" action='@Url.Action("AddNew", "EmploymentCompanyContactVisitLog")' method="post" enctype="multipart/form-data">
            <input type="hidden" name="CompanyContactId" value="@this.ViewBag.Contact.Id" />
            <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px;">
                <tr>
                    <td class='l-table-edit-td'>访谈日期</td>
                    <td class='l-table-edit-td'><input type='text' id='Time' name="Time" ltype='text' /></td>
                    <td class='l-table-edit-td'>访谈人员</td>
                    <td class='l-table-edit-td'>
                        <input name='f_VisitorId' type='text' id='f_VisitorId' ltype='text' />
                        <input name='VisitorId' type='hidden' id='VisitorId' />
                    </td>
                    <td class='l-table-edit-td'>访谈类型</td>
                    <td class='l-table-edit-td'>
                        <select id="Type" name="Type">
                            <option value="电访">电访</option>
                            <option value="面访">面访</option>
                        </select>
                    </td>
               </tr>
                <tr><td colspan="10" class='l-table-edit-td'>访谈内容：<br /><textarea name='Content' id='Content' ltype='text' class="l-textarea" style="width:100%;height:200;"></textarea></td></tr>
                <tr><td colspan="10" class='l-table-edit-td'><input type="submit" id="btnAdd" value="录入" /></td></tr>
            </table>
        </form>
    </div>
</body>
</html>

Cn.Com.Sve.OA.Web/Views/EmploymentCompanyContactVisitLog/EditSync.cshtml
@model Cn.Com.Sve.OA.Entities.EmploymentCompanyContactVisitLog

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Aqua/css/ligerui-all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/Gray/css/all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/ligerUI/skins/ligerui-icons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/lib/css/common.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Content/lib/jquery/jquery-1.7.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.widget.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.position.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery/ui/jquery.ui.autocomplete.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/ligerUI/js/ligerui.all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.metadata.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/messages_cn.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/jquery-validation/jquery.form.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/js/LG.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/lib/json2.js")" type="text/javascript"></script>
    <style type="text/css">
        body {
            font-size: 12px;
        }

        .l-table-edit {
        }

        .l-table-edit-td {
            padding: 4px;
        }

        .l-button-submit, .l-button-reset {
            width: 80px;
            float: left;
            margin-left: 10px;
            padding-bottom: 2px;
        }

        .l-verify-tip {
            left: 230px;
            top: 120px;
            z-index: 9999;
        }
    </style>
    <style type="text/css">
	.ui-autocomplete-loading { background: white url('@Url.Content("~/Content/themes/base/images/ui-anim_basic_16x16.gif")') right center no-repeat; }
	#f_UserName { width: 25em; }
    </style>
    <script type="text/javascript">
        $(function () {
            $("#Time").ligerDateEditor({ initValue: '@String.Format("{0:d}",this.Model.Time)' });
            $("#f_VisitorId").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("Suggest","User")',
                        dataType: "json",
                        data: {
                            qty: 12,
                            prefix: request.term
                        },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item.Name,
                                    value: item.Id
                                }
                            }));
                        }
                    });
                },
                minLength: 1,
                select: function (event, ui) {
                    $("#VisitorId").val(ui.item.value);
                    $("#f_VisitorId").val(ui.item.label);
                    return false;
                },
                open: function () {
                    $(this).removeClass("ui-corner-all").addClass("ui-corner-top");
                },
                close: function () {
                    $(this).removeClass("ui-corner-top").addClass("ui-corner-all");
                }
            });
            $("#frmCondition").ligerForm();

            $("#VisitorId").val("@this.Model.VisitorId");
            $("#f_VisitorId").val("@this.Model.Visitor.Name");

        });
    </script>
</head>
<body style="padding: 10px; height: 100%; text-align: center;">
    <div id="pnlStudentInfo" style="width: 98%">
        <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px; border: 1 solid black;" border="1">
            <tr>
                <td class='l-table-edit-td'>就业企业：@this.Model.CompanyContact.Company.Name</td>
                <td class='l-table-edit-td'>联系人：@this.Model.CompanyContact.Name</td>
                <td class='l-table-edit-td'>职务：@this.Model.CompanyContact.Position</td>
                <td class='l-table-edit-td'>手机：@this.Model.CompanyContact.Mobile</td>
            </tr>
            <tr>
                <td class='l-table-edit-td'>电话：@this.Model.CompanyContact.Telephone</td>
                <td class='l-table-edit-td'>QQ：@this.Model.CompanyContact.QQ</td>
                <td class='l-table-edit-td'>邮箱：@this.Model.CompanyContact.Email</td>
                <td class='l-table-edit-td'>备注：@this.Model.CompanyContact.Introduction</td>
            </tr>
        </table>
    </div>
    <div id="pnlByForm" style="width: 98%">
        <form id="frmCondition" class="l-form" action='@Url.Action("UpdateSync", "EmploymentCompanyContactVisitLog")' method="post" enctype="multipart/form-data">
            <input type="hidden" name="Id" value="@this.Model.Id" />
            <input type="hidden" name="CompanyContactId" value="@this.Model.CompanyContact.Id" />
            <table cellpadding="0" cellspacing="0" class="l-table-edit" style="width:800px">
                <tr>
                    <td class='l-table-edit-td'>访谈日期</td>
                    <td class='l-table-edit-td'><input type='text' id='Time' name="Time" ltype='text' /></td>
                    <td class='l-table-edit-td'>访谈人员</td>
                    <td class='l-table-edit-td'>
                        <input name='f_VisitorId' type='text' id='f_VisitorId' ltype='text' />
                        <input name='VisitorId' type='hidden' id='VisitorId' />
                    </td>
                    <td class='l-table-edit-td'>访谈类型</td>
                    <td class='l-table-edit-td'>
                        <select id="Type" name="Type">
                            @if (this.Model.Type.Equals("电访")) {
                                <option value="电访" selected="selected">电访</option>
                            } else {
                                <option value="电访">电访</option>
                            }
                            @if (this.Model.Type.Equals("面访")) {
                                <option value="面访" selected="selected">面访</option>
                            } else {
                                <option value="面访">面访</option>
                            }
                        </select>
                    </td>
                </tr>
                <tr><td colspan="10" class='l-table-edit-td'>访谈内容：<br /><textarea name='Content' id='Content' ltype='text' class="l-textarea" style="width:100%;height:200;">@this.Model.Content</textarea></td></tr>
                <tr><td colspan="10" class='l-table-edit-td'><input type="submit" id="btnAdd" value="更新" /></td></tr>
            </table>
        </form>
    </div>
</body>
</html>